# Generated by Django 4.2.6 on 2023-11-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('ongoing', models.BooleanField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
